### ISSUE TITLE
Arduino IDE library manager gives old version without support for SAMD21

### ISSUE THREAD

**Issue by HamishB** [adafruit/MAX31850_OneWire#1]
Hi,

This is more of a deployment request than a code bug, but I guess deployment is part of the development process, so..

If you install this library through the Arduino IDE's library manager, you get version 1.0.0, which does not have support for the SAMD21, and when you try to compile for the Adafruit Feather M0 you get an error to "Please define I/O register types here".  Downloading the code directly from github gets you version 1.0.1 which does support the M0 (and the ESP8266).

Or maybe the modern version of OneWire now contains what is needed to talk to the MAX31850? I mention that as I notice the version this library is based on is somewhat ancient. It's unclear to me what changes are needed to patch MAX31850 support from this library into the modern upstream OneWire since the initial commit to this one already had the changes applied (and I'm not sure how to do cross project diffs within github?).

many thanks,
Hamish

**Comment by ladyada** [comment]
hiya its been bumped
thx!
