### ISSUE TITLE
Support for SAMD21E18A (Trinket M0)

### ISSUE THREAD

**Issue by HamishB** [adafruit/MAX31850_OneWire#5]
Hi,

Trying to use a DS18B20 temperature sensor with a Trinket M0 fails in OneWire.h line 167 with:
```
#else
#error "Please define I/O register types here"
#endif
```

It seems that the library knows about `defined(__SAMD21G18A__)` but not the SAMD21E18A define.

Am I correct in surmising from the datasheet that the only difference between the "G" (Feather M0) and the "E" (Trinket M0) is simply the number of physical pins on the chip, and that all registers/code written for a Feather M0 will also work on an Trinket M0? (with fewer GPIO pins available of course)

This patch seems to work:

```
--- OneWire.h.ORIG	2020-06-27 04:23:54.000000000 +1200
+++ OneWire.h	2021-04-29 17:51:58.515989972 +1200
@@ -129,7 +129,7 @@
 #define DIRECT_WRITE_LOW(base, mask) (GPOC = (mask)) // GPIO_OUT_W1TC_ADDRESS
 #define DIRECT_WRITE_HIGH(base, mask) (GPOS = (mask)) // GPIO_OUT_W1TS_ADDRESS
 
-#elif defined(__SAMD21G18A__)
+#elif defined(__SAMD21G18A__) || defined(__SAMD21E18A__)
 #define PIN_TO_BASEREG(pin) portModeRegister(digitalPinToPort(pin))
 #define PIN_TO_BITMASK(pin) (digitalPinToBitMask(pin))
 #define IO_REG_TYPE uint32_t
```

It is left as an exercise for the author to decide if the two chips should be sorted alphabetically or by volume shipped. :o)

thanks,
Hamish

**Comment by ladyada** [comment]
great work! please submit a PR and we can merge it in :)

**Comment by ladyada** [comment]
added!
